# Generated by Django 4.1 on 2022-08-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='IDADE')),
                ('cpf', models.TextField(verbose_name='CPF')),
                ('ativa', models.BooleanField(verbose_name='ativa')),
            ],
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('local', models.TextField(verbose_name='Local')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('pessoas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividas', to='dividas_p.pessoaf')),
            ],
        ),
    ]
