# Generated by Django 4.1 on 2022-08-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dividas_p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.TextField(verbose_name='CPF')),
                ('pessoaF', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_user', to='dividas_p.pessoaf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
